#
# Simple playbook to update root password
#
# NOTE: You need 'passlib' on localhost (eg 'apt install python-passlib')
#
# Example, update one host:
#
#   $ ansible-playbook -i <inventory> update_root_password.yaml "-e host=norway" -l res-web1.bisnor.local
#
# Example, update host group:
#
#   $ ansible-playbook -i <inventory> update_root_password.yaml "-e host=norway"
#

---

- hosts: all
  become: false

  tasks:
    - name: Check 'host' variable is set
      assert:
        that:
          - "false"
        msg: Execute playbook with '-e host=$hosts' (hosts = hostgroup or fqdn)
      when: (host is undefined) or (host | trim == '')
      delegate_to: localhost

- hosts: '{{ host }}'
  become: yes
  vars_prompt:
  - name: rootpw
    prompt: "Enter Password (to be encrypted): "
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes

  tasks:
  - name: Change Password
    user:
      name: root
      password: "{{ rootpw }}"
      update_password: always
